apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-shard-rc1
  labels:
    name: mongo-shard-rc
spec:
  replicas: 1
  selector:
    name: mongo-shard-node1
  template:
    metadata:
      labels:
        name: mongo-shard-node1
    spec:
      containers:
      - name: mongo-shard-node1
        image: index.caicloud.io/caicloud/mongo:3.0.5
        command:
        - mongod
        - "--configsvr"
        - "--replSet"
        - "configReplSet"
        - "--dbpath"
        - "/data/configdb"
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-persistent-storage1
          mountPath: /data/configdb
      volumes:
      - name: mongo-persistent-storage1
        emptyDir: {}