apiVersion: v1
kind: ReplicationController
metadata:
  name: mongo-replica-rc1
  labels:
    name: mongo-replica-rc
spec:
  replicas: 1
  selector:
    name: mongo-replica-node1
  template:
    metadata:
      labels:
        name: mongo-replica-node1
    spec:
      containers:
      - name: mongo-replica-node1
        image: index.caicloud.io/caicloud/mongo:3.2
        command:
        - mongod
        - "--replSet"
        - my_replica_set
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-replica-storage1
          mountPath: /data/db
      volumes:
      - name: mongo-replica-storage1
        emptyDir: {}